# Secret de démo pour cluster local kind. Ne pas réutiliser en production.
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql-repl
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpass123"
  MYSQL_REPLICATION_USER: "repl_user"
  MYSQL_REPLICATION_PASSWORD: "replpass123"
